"""Add allowed_domains to tenants

Revision ID: 2a35d2bb1e8b
Revises: e7656e020f1a
Create Date: 2026-09-10 18:12:14.589049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a35d2bb1e8b'
down_revision: Union[str, None] = 'e7656e020f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tenants',
        sa.Column('allowed_domains', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'allowed_domains')
    # ### end Alembic commands ###
