export const tokens = {
  color: {
    bg: 'rgb(var(--color-bg))',
    surface: 'rgb(var(--color-surface))',
    surfaceMuted: 'rgb(var(--color-surface-muted))',
    fg: 'rgb(var(--color-fg))',
    fgMuted: 'rgb(var(--color-fg-muted))',
    fgSubtle: 'rgb(var(--color-fg-subtle))',
    border: 'rgb(var(--color-border))',
    primary: 'rgb(var(--color-primary))',
    primaryHover: 'rgb(var(--color-primary-hover))',
    primaryFg: 'rgb(var(--color-primary-fg))',
    success: 'rgb(var(--color-success))',
    successSoft: 'rgb(var(--color-success-soft))',
    successFg: 'rgb(var(--color-success-fg))',
    warning: 'rgb(var(--color-warning))',
    warningSoft: 'rgb(var(--color-warning-soft))',
    warningFg: 'rgb(var(--color-warning-fg))',
    danger: 'rgb(var(--color-danger))',
    dangerSoft: 'rgb(var(--color-danger-soft))',
    dangerFg: 'rgb(var(--color-danger-fg))',
    info: 'rgb(var(--color-info))',
    infoSoft: 'rgb(var(--color-info-soft))',
    infoFg: 'rgb(var(--color-info-fg))',
  },
  fontFamily: {
    sans: 'Inter Variable, Inter, system-ui, sans-serif',
    mono: 'JetBrains Mono, ui-monospace, monospace',
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
  },
  borderRadius: {
    sm: '0.375rem',
    md: '0.5rem',
    lg: '0.75rem',
  },
} as const;
